DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

Mkonline/urls.py
# _*_ encoding:utf-8 _*_
"""Mkonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# from django.contrib import admin
# from django.conf.urls import url
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin

from users.views import LoginView, LogoutView, ForgetPWdView, RegisterView, ActiveUserView, ResetPwdView, ModifyPwdView
from Mkonline.settings import MEDIA_ROOT
# from Mkonline.settings import STATIC_ROOT

from operations.views import IndexView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),    # required by ueditor
    path('captcha/', include('captcha.urls')),

    # 配置上传文件的URL访问路径
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # User Register  process control:
    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('active/<str:active_code>', ActiveUserView.as_view(), name="user_active"),
    path('forgetpwd/', ForgetPWdView.as_view(), name="forget_pwd"),
    path('reset/<str:reset_code>', ResetPwdView.as_view(), name="reset_pwd"),
    path('modifypwd/', ModifyPwdView.as_view(), name="modify_pwd"),

    # 机构相关页面
    path('org/', include('organization.urls', namespace='org')),

    # 课程相关页面
    path('course/', include('courses.urls', namespace='courses')),

    # 用户操作相关页面
    path('op/', include('operations.urls', namespace='op')),

    # 用户个人中心
    path('users/', include('users.urls', namespace='users')),


]

apps/courses/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentsView, CourseVideoView

app_name = 'courses'
urlpatterns = [

    path('list/', CourseListView.as_view(), name='list'),
    path('<int:course_id>/detail/', CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/lesson/', CourseLessonView.as_view(), name='lesson'),
    path('<int:course_id>/comments/', CourseCommentsView.as_view(), name='comments'),
    path('<int:course_id>/video/<int:video_id>', CourseVideoView.as_view(), name='video'),

]

apps/operations/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import AddFavView, CommentView


app_name = 'operations'
urlpatterns = [
    path('fav/', AddFavView.as_view(), name='fav'),
    path('comment/', CommentView.as_view(), name='comment'),
    # path('add_ask/', AddAskView.as_view(), name='add_ask'),
    #
    # path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    # path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    # path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    # path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),
]

apps/organization/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import OrgView, AddAskView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, TeachersView
from .views import TeacherDetailView

app_name = 'organization'
urlpatterns = [
    path('list/', OrgView.as_view(), name='list'),
    path('add_ask/', AddAskView.as_view(), name='add_ask'),

    path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),

    path('teachers/', TeachersView.as_view(), name='teachers'),
    path('teachers/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/organization/models.py
# _*_ encoding:utf-8 _*_
"""
    2-培训机构和教师主数据
        2.1 CityDict               城市信息
        2.2 CourseOrg              课程机构基本信息
        2.3 Teacher                教师基本信息

"""

from django.db import models

from users.models import BaseModel


# Create your models here.


class CityDict(BaseModel):
    """
    2.1 CityDict               城市信息
    """
    name = models.CharField(max_length=20, verbose_name=u"城市名称")
    desc = models.CharField(max_length=200, verbose_name=u"描述")

    class Meta:
        verbose_name = u"城市"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


CATEGORY_CHOICES = (
    ("pxjg", "培训机构"),
    ("gx", "高校"),
    ("gr", "个人"),
)

RECOM_STARS = (
    (0, "0"),
    (1, "*"),
    (2, "**"),
    (3, "***"),
    (4, "****"),
    (5, "*****"),
)


class CourseOrg(BaseModel):
    """
    2.2 CourseOrg              课程机构基本信息
    """
    name = models.CharField(max_length=50, verbose_name=u"机构名称")
    desc = models.TextField(verbose_name=u"机构描述")
    tag = models.CharField(default=u"全国知名", max_length=10, verbose_name=u"机构标签")
    category = models.CharField(default="pxjg", max_length=4, choices=CATEGORY_CHOICES, verbose_name=u"机构类别")
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏数")
    image = models.ImageField(upload_to="org/%Y/%m", verbose_name=u"封面图")
    address = models.CharField(max_length=150, verbose_name=u"机构地址")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    course_nums = models.IntegerField(default=0, verbose_name=u"课程数")

    is_auth = models.BooleanField(default=False, verbose_name=u"是否认证")
    is_gold = models.BooleanField(default=False, verbose_name=u"是否金牌")

    recom_stars = models.IntegerField(default=0, choices=RECOM_STARS, verbose_name=u"推荐指数")

    city = models.ForeignKey(CityDict, on_delete=models.CASCADE, verbose_name=u"所在城市")

    # 因为courses的一个外键是CourseOrg,所以可以反向去到courses的数据
    def courses(self):
        courses = self.course_set.filter(is_classics=True)[:3]
        return courses

    def teachers(self):
        return self.teacher_set.all()

    class Meta:
        verbose_name = u"课程机构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name        # 必须是必填项字段


from apps.users.models import UserProfile
class Teacher(BaseModel):
    """
    2.3 Teacher                教师基本信息
    """
    user = models.OneToOneField(UserProfile, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=u"系统用户")
    org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name=u"所属机构")
    name = models.CharField(max_length=50, verbose_name=u"教师名")
    work_years = models.IntegerField(default=0, verbose_name=u"工作年限")
    work_company = models.CharField(max_length=50, verbose_name=u"就职公司")
    work_position = models.CharField(max_length=50, verbose_name=u"公司职位")
    points = models.CharField(max_length=50, verbose_name=u"教学特点")
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏数")
    age = models.IntegerField(default=26, verbose_name=u"年龄")
    image = models.ImageField(upload_to="teacher/%Y/%m", max_length=100, verbose_name=u"头像")

    is_auth = models.BooleanField(default=False, verbose_name=u"是否认证")

    class Meta:
        verbose_name = u"教师"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def course_nums(self):
        return self.course_set.all().count()

apps/organization/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/1/30 9:27 下午'
"""
"""
import re

from django import forms

from apps.operations.models import UserAsk


class AddAskForm(forms.ModelForm):
    # 从新定义Model里的mobile字段，因为在那里无法现在最小长度。
    mobile = forms.CharField(max_length=11, min_length=11, required=True)

    class Meta:
        model = UserAsk
        fields = ["name", "mobile", "course_name"]

    def clean_mobile(self):
        """
        验证手机号码是否合法
        :return:
        """

        mobile = self.cleaned_data["mobile"]
        regex_mobile = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"
        p = re.compile(regex_mobile)
        if p.match(mobile):
            return mobile
        else:
            raise forms.ValidationError("手机号码非法", code="mobile_invalid")

apps/organization/views.py
# _*_ encoding:utf-8 _*_
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django.db.models import Q

from pure_pagination import Paginator, PageNotAnInteger

from apps.organization.models import CourseOrg, CityDict, Teacher
from apps.organization.forms import AddAskForm
from apps.operations.models import UserFavorite
from apps.courses.models import Course


class TeacherDetailView(View):
    def get(self, request, teacher_id, *args, **kwargs):
        teacher_detail = Teacher.objects.get(id=int(teacher_id))
        hot_teachers = Teacher.objects.all().order_by("-click_nums")[:5]
        all_courses = Course.objects.filter(teacher_id=teacher_detail.id)

        has_fav_teacher = False
        has_fav_org = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=teacher_id, fav_type='3'):
                has_fav_teacher = True

            if UserFavorite.objects.filter(user=request.user, fav_id=teacher_detail.org.id, fav_type='2'):
                has_fav_org = True

        # 对课程数据进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_courses, per_page=3, request=request)
        all_courses = p.page(page)

        return render(request, "organization/teacher-detail.html", {
            "teacher_detail": teacher_detail,
            "all_courses": all_courses,
            "teacher_id": teacher_id,
            "hot_teachers": hot_teachers,
            "has_fav_teacher": has_fav_teacher,
            "has_fav_org": has_fav_org,
        })


class TeachersView(View):
    def get(self, request, *args, **kwargs):
        all_teachers = Teacher.objects.all()
        hot_teachers = Teacher.objects.all().order_by("-click_nums")[:3]

        # 按关键字搜索
        keywords = request.GET.get("keywords", "")
        s_type = "teacher"
        if keywords:
            all_teachers = all_teachers.filter(Q(name__icontains=keywords))

        sort = request.GET.get("sort", "")
        if sort == "hot":
            all_teachers = all_teachers.order_by("-click_nums")

        # 对教师数据进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_teachers, per_page=2, request=request)
        teachers = p.page(page)

        return render(request, "organization/teachers-list.html", {
            "teachers": teachers,
            "sort": sort,
            "hot_teachers": hot_teachers,
            "keywords": keywords,
            "s_type": s_type,
        })


class OrgDescView(View):
    def get(self, request, org_id, *args, **kwargs):
        current_page = 'desc'
        course_org = CourseOrg.objects.get(id=int(org_id))
        course_org.click_nums += 1
        course_org.save()

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type='2'):
                has_fav = True

        return render(request, "org-detail-desc.html", {
            "course_org": course_org,
            "current_page": current_page,
            "has_fav": has_fav,
        })


class OrgCourseView(View):
    def get(self, request, org_id, *args, **kwargs):
        current_page = "course"
        course_org = CourseOrg.objects.get(id=int(org_id))
        course_org.click_nums += 1
        course_org.save()

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type='2'):
                has_fav = True

        all_courses = course_org.course_set.all()

        # 对课程数据进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_courses, per_page=3, request=request)
        courses = p.page(page)

        return render(request, "org-detail-course.html", {
            "all_courses": courses,
            "course_org": course_org,
            "current_page": current_page,
            "has_fav": has_fav,
        })


class OrgTeacherView(View):
    def get(self, request, org_id, *args, **kwargs):
        current_page = "teacher"
        course_org = CourseOrg.objects.get(id=int(org_id))
        course_org.click_nums += 1
        course_org.save()

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type='2'):
                has_fav = True
        all_teachers = course_org.teacher_set.all()

        return render(request, "org-detail-teachers.html", {
            "all_teachers": all_teachers,
            "course_org": course_org,
            "current_page": current_page,
            "has_fav": has_fav,
        })


class OrgHomeView(View):
    def get(self, request, org_id, *args, **kwargs):
        current_page = "homepage"
        course_org = CourseOrg.objects.get(id=int(org_id))
        course_org.click_nums += 1
        course_org.save()

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type='2'):
                has_fav = True

        all_courses = course_org.course_set.all()[:3]
        all_teachers = course_org.teacher_set.all()[:1]

        return render(request, "org-detail-homepage.html", {
            "all_courses": all_courses,
            "all_teachers": all_teachers,
            "course_org": course_org,
            "current_page": current_page,
            "has_fav": has_fav,
        })


class AddAskView(View):
    """
    处理用户咨询
    """
    def post(self, request, *args, **kwargs):
        userask_form = AddAskForm(request.POST)
        if userask_form.is_valid():
            userask_form.save(commit=True)
            return JsonResponse({
                "status": "success"
            })
        else:
            return JsonResponse({
                "status": "fail",
                "msg": "添加出错"
            })


class OrgView(View):
    """
    课程机构列表功能
    """
    def get(self, request, *args, **kwargs):
        # 从数据库中获取数据
        all_orgs = CourseOrg.objects.all()
        all_cities = CityDict.objects.all()
        hot_orgs = all_orgs.order_by('-click_nums')[:3]

        # 按关键字搜索
        keywords = request.GET.get("keywords", "")
        s_type = "org"
        if keywords:
            all_orgs = all_orgs.filter(Q(name__icontains=keywords)|Q(desc__icontains=keywords))

        # 通过机构类别对课程机构进行筛选
        category = request.GET.get("ct", "")
        if category:
            all_orgs = all_orgs.filter(category=category)

        # 通过所在城市对课程机构进行筛选
        city_id = request.GET.get("city", "")
        if city_id:
            if city_id.isdigit():
                all_orgs = all_orgs.filter(city_id=int(city_id))

        # 对机构进行排序
        sort = request.GET.get("sort", "")
        if sort == "students":
            all_orgs = all_orgs.order_by("-students")
        elif sort == "courses":
            all_orgs = all_orgs.order_by("-course_nums")

        org_nums = all_orgs.count()

        # 对课程机构数据进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_orgs, per_page=3, request=request)
        orgs = p.page(page)

        return render(request, "org-list.html", {
            "all_orgs": orgs,
            "org_nums": org_nums,
            "all_cities": all_cities,
            "category": category,
            "city_id": city_id,
            "sort": sort,
            "hot_orgs": hot_orgs,
            "keywords": keywords,
            "s_type" : s_type,
        })

apps/organization/templates/organization/teacher-detail.html
{% extends 'base.html' %}
<title>{% block title %} 讲师详情 - 慕学在线网{% endblock %}</title>

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'org:teachers' %}">授课讲师</a>></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
	<div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">
            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="{{teacher_detail.image.url}}"/>
                            </div>
                            <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                     {% if has_fav_teacher %}已收藏{% else %}收藏{% endif %}
                                </span>
                                <span class="fr btn2 shareBtn bdsharebuttonbox"
                                      data-text="授课教师-{{ teacher_detail.name }}-{{ teacher_detail.org.name }}"
                                      data-desc="我在#{{ teacher_detail.org.name }}#发现了"
                                      data-comment="{{ teacher_detail.name }}，
                                      工作年限：{% if teacher_detail.work_years > 0 %}{{ teacher_detail.work_years }}年{% else %}无{% endif %}；
                                      学历：本科；
                                      所在公司：{{ teacher_detail.org.name }}&nbsp;；经典案例：django入门和深入；flask入门"
                                      data-url="{% url 'org:teacher_detail' teacher_detail.id %}">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                            </div>
                        </dt>
                        <dd>
                            <a href="{% url 'org:teacher_detail' teacher_detail.id %}">
                                <h1>{{ teacher_detail.name }}<span class="key picbig">金牌讲师</span></h1>
                            </a>
                            <ul class="cont">
                                <li>工作年限：<span>{{ teacher_detail.work_years }}年</span></li>
                                <li>就职公司：<span>{{ teacher_detail.work_company }}</span></li>
                                <li>工作职位：<span>{{ teacher_detail.work_position }}&nbsp;</span></li>
                                <li>教学特点：<span>{{ teacher_detail.points }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="butler_detail_cont clearfix">
                <div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="{% url 'org:teacher_detail' teacher_detail.id %}">全部课程</a> </li>
					</ul>
				</div>
                    <div class="companycenter">
                        <div class="group_list brief">
                            {% for course in all_courses.object_list %}
                            <div class="module1_5 box">
                                <a href="{% url 'courses:detail' course.id %}">
                                    <img width="214" height="190" class="scrollLoading" src="{{ course.image.url }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:detail' course.id %}"><h2>{{ course.name}}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ course.course_org.name }}</span>
                                    <span class="star fr  notlogin" data-favid="15">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                <div class="pageturn">
                        <ul class="pagelist">
                        {% if all_courses.has_previous %}
                            <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a></li>
                        {% endif %}

                        {% for page in all_courses.pages %}
                        {% if page %}
                            {% ifequal page all_courses.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="none">...</li>
                        {% endif %}
                        {% endfor %}
                        {% if all_courses.has_next %}
                            <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a> </li>
                        {% endif %}

            </ul>
        </div>
            </div>
            </div>
        </div>
        <div class="fr list">
             <div class="butler_detail_list">
                <div class="right butler-company-box">
                <div class="head">
                    <h1>{{ teacher_detail.org.name }}</h1>
                    <p>{{ teacher_detail.org.tag }}</p>
                </div>
                <div class="pic">
                    <a href="{% url 'org:org_home' teacher_detail.org.id%}">
                        <img width="150" height="80" src="{{ teacher_detail.org.image.url }}"/>
                    </a>
                </div>
                <a href="{% url 'org:org_home' teacher_detail.org.id%}">
                    <h2 class="center">{{ teacher_detail.org.name }}</h2>
                </a>
                <p class="center tell">地址：{{ teacher_detail.org.address }}</p>
                <a class="btn" id="jsRightBtn">{% if has_fav_org %}已收藏{% else %}收藏{% endif %}</a>
            </div>
            </div>
            <div class="butler_detail_cont">
                <div class="butler_list_box">
                    <div class="right layout">
                        <div class="head">讲师排行榜TOP5</div>
                        {% for hot_teacher in hot_teachers %}
                        <dl class="des">
                            <span class="num fl">{{ forloop.counter }}</span>
                            <a href="{% url 'org:teacher_detail' hot_teacher.id %}">
                                <dt>
                                    <img width="50" height="50" class="scrollLoading" src="{{ hot_teacher.image.url }}"/>
                                </dt>
                            </a>
                            <dd>
                                <a href="{% url 'org:teacher_detail' hot_teacher.id %}">
                                    <h1 title="{{ hot_teacher.name }}">{{ hot_teacher.name }}</h1>
                                </a>
                                <p>工作年限：<span>{% if hot_teacher.work_years > 0 %}{{ hot_teacher.work_years }}年{% else %}无{% endif %}</span></p>
                            </dd>
                        </dl>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'op:fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}
$(document).ready(function() {
    $('#jsLeftBtn').on('click', function () {
        add_fav($(this), {{ teacher_detail.id }}, 3);
    });
});
$(document).ready(function() {
    $('#jsRightBtn').on('click', function () {
        add_fav($(this), {{ teacher_detail.org.id }}, 2);
    });
});


</script>
<script>
		var shareUrl = '',
            shareText = '',
            shareDesc = '',
            shareComment = '';
        $(function () {
            $(".bdsharebuttonbox a").mouseover(function () {
                var type = $(this).attr('data-cmd'),
                    $parent = $(this).parent('.bdsharebuttonbox'),
                    fxurl = $parent.attr('data-url'),
                    fxtext = $parent.attr('data-text'),
                    fxdesc = $parent.attr('data-desc'),
                    fxcomment = $parent.attr('data-comment');
                switch (type){
                    case 'tsina':
                    case 'tqq':
                    case 'renren':
                            shareUrl = fxurl;
                            shareText = fxdesc;
                            shareDesc = '';
                            shareComment = '';
                        break;
                    default :
                            shareUrl = fxurl;
                            shareText = fxtext;
                            shareDesc = fxdesc;
                            shareComment = fxcomment;
                        break;
                }
            });
        });
        function SetShareUrl(cmd, config) {
            if (shareUrl) {
                config.bdUrl = "{{ SITE_URL }}" + shareUrl;
            }
            if(shareText){
                config.bdText = shareText;
            }
            if(shareDesc){
                config.bdDesc = shareDesc;
            }
            if(shareComment){
                config.bdComment = shareComment;
            }

            return config;
        }
        window._bd_share_config = {
            "common": {
                "onBeforeClick":SetShareUrl,
                "bdMini":"2",
                "searchPic":"1",
                "bdMiniList":false
            },
            "share": {
                "bdSize":"16"
            }
        };
		with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?cdnversion='+~(-new Date()/36e5)];
</script>

{% endblock %}