DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

Mkonline/urls.py
# _*_ encoding:utf-8 _*_
"""Mkonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# from django.contrib import admin
# from django.conf.urls import url
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin

from users.views import LoginView, LogoutView, ForgetPWdView, RegisterView, ActiveUserView, ResetPwdView, ModifyPwdView
from Mkonline.settings import MEDIA_ROOT
# from Mkonline.settings import STATIC_ROOT

from operations.views import IndexView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),    # required by ueditor
    path('captcha/', include('captcha.urls')),

    # 配置上传文件的URL访问路径
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # User Register  process control:
    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('active/<str:active_code>', ActiveUserView.as_view(), name="user_active"),
    path('forgetpwd/', ForgetPWdView.as_view(), name="forget_pwd"),
    path('reset/<str:reset_code>', ResetPwdView.as_view(), name="reset_pwd"),
    path('modifypwd/', ModifyPwdView.as_view(), name="modify_pwd"),

    # 机构相关页面
    path('org/', include('organization.urls', namespace='org')),

    # 课程相关页面
    path('course/', include('courses.urls', namespace='courses')),

    # 用户操作相关页面
    path('op/', include('operations.urls', namespace='op')),

    # 用户个人中心
    path('users/', include('users.urls', namespace='users')),


]

apps/courses/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentsView, CourseVideoView

app_name = 'courses'
urlpatterns = [

    path('list/', CourseListView.as_view(), name='list'),
    path('<int:course_id>/detail/', CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/lesson/', CourseLessonView.as_view(), name='lesson'),
    path('<int:course_id>/comments/', CourseCommentsView.as_view(), name='comments'),
    path('<int:course_id>/video/<int:video_id>', CourseVideoView.as_view(), name='video'),

]

apps/operations/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import AddFavView, CommentView


app_name = 'operations'
urlpatterns = [
    path('fav/', AddFavView.as_view(), name='fav'),
    path('comment/', CommentView.as_view(), name='comment'),
    # path('add_ask/', AddAskView.as_view(), name='add_ask'),
    #
    # path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    # path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    # path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    # path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),
]

apps/organization/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import OrgView, AddAskView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, TeachersView
from .views import TeacherDetailView

app_name = 'organization'
urlpatterns = [
    path('list/', OrgView.as_view(), name='list'),
    path('add_ask/', AddAskView.as_view(), name='add_ask'),

    path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),

    path('teachers/', TeachersView.as_view(), name='teachers'),
    path('teachers/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path
# from django.views.generic import TemplateView

from .views import UserInfoView, UploadImageView, ChangePwdView, MyCourseView, MyFavOrgView, MyFavCourseView
from .views import MyFavTeacherView, MyMessagesView
# from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
    path('info/', UserInfoView.as_view(), name='user_info'),
    path('image/upload/', UploadImageView.as_view(), name='image_upload'),
    path('update/pwd/', ChangePwdView.as_view(), name='update_pwd'),
    path('mycourse/', MyCourseView.as_view(), name='mycourse'),
    # path('mycourse/', login_required(TemplateView.as_view(template_name="users/usercenter-mycourse.html"), login_url="/login/"), {"current_page": "mycourse"}, name='mycourse'),
    path('myfavorg/', MyFavOrgView.as_view(), name='myfavorg'),
    path('myfavteacher/', MyFavTeacherView.as_view(), name='myfavteacher'),
    path('myfavcourse/', MyFavCourseView.as_view(), name='myfavcourse'),
    path('mymessages/', MyMessagesView.as_view(), name='mymessages'),

]

apps/courses/models.py
# _*_ encoding:utf-8 _*_
"""
    3-Courses 课程主数据
        3.1 Course              课程基本信息
        3.2 Lesson              章节信息
        3.3 Video               视频
        3.4 CourseResource      课程资源
"""

from django.db import models

from users.models import BaseModel
from apps.organization.models import Teacher, CourseOrg

# Create your models here.

DEGREE_CHOICES = (
    ("cj", "初级"),
    ("zj", "中级"),
    ("gj", "高级"),
)


class Course(BaseModel):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name=u"讲师")
    course_org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name=u"课程机构")
    name = models.CharField(max_length=50, verbose_name=u"课程名")     # 所有字段没有特殊指定时，默认为必填项
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    degree = models.CharField(choices=DEGREE_CHOICES, max_length=2, verbose_name=u"难度")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    notice = models.CharField(default="", max_length=300, verbose_name=u"课程公告")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name=u"")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10)
    youneed_know = models.CharField(default="", max_length=300, verbose_name=u"课程须知")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name=u"老师告诉你")

    is_classics = models.BooleanField(default=False, verbose_name=u"是否经典")
    is_banner = models.BooleanField(default=False, verbose_name=u"是否广告位")

    detail = models.TextField(verbose_name=u"课程详情")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        return self.lesson_set.all().count()


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    tag = models.CharField(max_length=100, verbose_name=u"标签")

    class Meta:
        verbose_name = u"课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(BaseModel):
    # on_delete 表示对应的外键数据被删除后，当前的数据将如何处理。
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    url = models.CharField(max_length=1000, verbose_name=u"访问地址")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"下载地址", max_length=200)

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/users/models.py
# _*_ encoding:utf-8 _*_
"""
    1-用户主数据，基本底层数据表
        1.1 UserProfile             用户信息
        1.2 EmailVerifyRecord       邮箱验证信息
        # 1.3 Banner                  轮播图
"""

from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class BaseModel(models.Model):
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        abstract = True


GENDER_CHOICES = (
    ("male", "男"),
    ("female", "女")
)


class UserProfile(AbstractUser):
    """
    1.1 UserProfile             用户信息
    继承系统的用户信息后，再添加本系统需要的扩展用户字段
    """
    nick_name = models.CharField(max_length=50, default=u"", verbose_name=u"昵称")
    birthday = models.DateField(null=True, blank=True, verbose_name=u"生日")
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="female", verbose_name=u"性别")
    address = models.CharField(max_length=100, default=u"", verbose_name=u"联系地址")
    mobile = models.CharField(max_length=11, null=True, blank=True, verbose_name=u"手机号码")
    image = models.ImageField(max_length=100, upload_to="user_image/%Y/%m",
                              default=u"user_image/default.png", verbose_name=u"用户头像")

    class Meta:
        verbose_name = u"用户信息"
        verbose_name_plural = verbose_name

    def unread_nums(self):
        # 未读消息数量
        return self.usermessage_set.filter(has_read=False).count()

    def __str__(self):
        if self.nick_name:
            return self.nick_name
        else:
            return self.username


class EmailVerifyRecord(models.Model):
    """
    1.2 EmailVerifyRecord       邮箱验证信息
    """
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    send_type = models.CharField(choices=(("register", u"注册"), ("forget", u"忘记密码")),
                                 max_length=10, verbose_name=u"验证码类型")
    # 不要使用now()， 需要在实例化时生成时间
    send_time = models.DateTimeField(default=datetime.now, verbose_name=u"发送时间")

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)


# class Banner(BaseModel):
#     """
#     1.3 Banner                  轮播图
#     """
#     title = models.CharField(max_length=100, verbose_name=u"标题")
#     image = models.ImageField(upload_to="banner/%Y/%m", verbose_name=u"轮播图", max_length=100)
#     url = models.URLField(max_length=200, verbose_name=u"访问地址")
#     index = models.IntegerField(default=100, verbose_name=u"播放顺序")
#
#     class Meta:
#         verbose_name = u"轮播图"
#         verbose_name_plural = verbose_name
#
#     def __str__(self):
#         return self.title

apps/users/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/1/30 9:27 下午'
"""
"""
from django import forms
from captcha.fields import CaptchaField

from users.models import UserProfile


class ChangePwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

    def clean(self):
        pwd1 = self.cleaned_data["password1"]
        pwd2 = self.cleaned_data["password2"]

        if pwd1 != pwd2:
            raise forms.ValidationError("密码不一致")
        return self.cleaned_data


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["nick_name", "gender", "birthday", "address"]


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["image"]


class DynamicLoginForm(forms.Form):
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误！"})
    captcha1 = CaptchaField(error_messages={"invalid": u"验证码错误！"})


class LoginForm(forms.Form):
    """
    这里的username 和 password应该是和login页面上的一致，否则将无法验证，
    利用form功能设计可以进行在完成网页验证工作之后， 和进行数据库操作之前，在Python&Django代码里完成更完善的数据验证工作
    """
    username = forms.CharField(required=True, min_length=3)
    password = forms.CharField(required=True, min_length=5)   # 密码最小长度为5位
    # captcha = CaptchaField(error_messages={"invalid": u"验证码错误！"})   # 重置系统关于invalid的标准翻译 - 认证码


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)  # 密码最小长度为5位
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误！"})   # 重置系统关于invalid的标准翻译 - 认证码
    # captcha = CaptchaField()


class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误！"})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)  # 密码最小长度为5位
    password2 = forms.CharField(required=True, min_length=5)  # 密码最小长度为5位

apps/users/templates/users/usercenter-fav-course.html
{% extends 'users/usercenter-base.html' %}

{% block title %} 我的收藏- 慕学在线网{% endblock %}

{% load static %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_form %}

 <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% if current_fav_page == 'myorg' %}active{% endif %}"><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li class="{% if current_fav_page == 'myteacher' %}active{% endif %}"><a href="{% url 'users:myfavteacher' %}">授课教师 </a></li>
                        <li class="{% if current_fav_page == 'mycourse' %}active{% endif %}"><a href="{% url 'users:myfavcourse' %}">公开课程</a></li>
                     </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:detail' course.id %}">
                                <img width="214" height="190" src="{{ course.image.url }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:detail' course.id %}"><h2>{{course.name}}</h2></a>
                                <span class="fl">时长：<i class="key">{{course.learn_times}}</i></span>
                                <span class="fr">学习人数：{{course.students}}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{course.course_org.name}}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{course.id}}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

{% block custom_js %}
<script type="text/javascript">
$('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            alert(favid)
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>
{% endblock %}

apps/users/templates/users/usercenter-fav-org.html
{% extends 'users/usercenter-base.html' %}

{% block title %} 我的收藏- 慕学在线网{% endblock %}

{% load static %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_form %}

 <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% if current_fav_page == 'myorg' %}active{% endif %}"><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li class="{% if current_fav_page == 'myteacher' %}active{% endif %}"><a href="{% url 'users:myfavteacher' %}">授课教师 </a></li>
                        <li class="{% if current_fav_page == 'mycourse' %}active{% endif %}"><a href="{% url 'users:myfavcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ org.image.url }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{org.name}}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    {% if org.is_auth %}
                                    <img src="{% static 'images/authentication.png' %}"/>
                                    {% endif %}
                                    {% if org.is_gold %}
                                    <img src="{% static 'images/gold.png' %}"/>
                                    {% endif %}
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>

{% endblock %}

{% block custom_js %}

<script type="text/javascript">
    $('.jsDeleteFav_org').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 2,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>

{% endblock %}

apps/users/templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter-base.html' %}

{% block title %} 我的收藏- 慕学在线网{% endblock %}

{% load static %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_form %}

 <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% if current_fav_page == 'myorg' %}active{% endif %}"><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li class="{% if current_fav_page == 'myteacher' %}active{% endif %}"><a href="{% url 'users:myfavteacher' %}">授课教师 </a></li>
                        <li class="{% if current_fav_page == 'mycourse' %}active{% endif %}"><a href="{% url 'users:myfavcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in teacher_list %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'org:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ teacher.image.url }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'org:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}{% if teacher.is_auth %}<span class="key">认证教师</span>{% endif %}
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{% if teacher.work_years > 0 %}{{ teacher.work_years }}年{% else %}无{% endif %}</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.course_set.all.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{teacher.work_position}}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{teacher.id}}"></div>
                        </dl>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>

{% endblock %}

{% block custom_js %}

<script type="text/javascript">
    $('.jsDeleteFav_teacher').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 3,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>

{% endblock %}

apps/users/templates/users/usercenter-info.html
{% extends 'users/usercenter-base.html' %}

{% block title %}个人信息- 慕学在线网{% endblock %}

{% load static %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_form %}
 <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{user.image.url}}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                         {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ user.nick_name | default_if_none:''}}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birthday" value="{{ user.birthday | default_if_none:'' | date:'Y-m-d'}}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if user.gender == 'male' %} checked="checked" {% endif %} >男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if user.gender == 'female' %} checked="checked" {% endif %} >女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ user.address }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
                        <li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input class="borderno" type="text" name="mobile" readonly="readonly" value="{{ user.mobile }}">
                            <span class="changeemai_btn green changephone-color">[修改]</span>
                        </li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
{#                            # find jsEditUserBtn in static/js/deco-user.js#}
						</li>
					</ul>
                {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}