DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

Mkonline/urls.py
# _*_ encoding:utf-8 _*_
"""Mkonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# from django.contrib import admin
# from django.conf.urls import url
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

import xadmin

from users.views import LoginView, LogoutView, ForgetPWdView, RegisterView, ActiveUserView, ResetPwdView, ModifyPwdView
from Mkonline.settings import MEDIA_ROOT
# from Mkonline.settings import STATIC_ROOT

from operations.views import IndexView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),    # required by ueditor
    path('captcha/', include('captcha.urls')),

    # 配置上传文件的URL访问路径
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # User Register  process control:
    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('active/<str:active_code>', ActiveUserView.as_view(), name="user_active"),
    path('forgetpwd/', ForgetPWdView.as_view(), name="forget_pwd"),
    path('reset/<str:reset_code>', ResetPwdView.as_view(), name="reset_pwd"),
    path('modifypwd/', ModifyPwdView.as_view(), name="modify_pwd"),

    # 机构相关页面
    path('org/', include('organization.urls', namespace='org')),

    # 课程相关页面
    path('course/', include('courses.urls', namespace='courses')),

    # 用户操作相关页面
    path('op/', include('operations.urls', namespace='op')),

    # 用户个人中心
    path('users/', include('users.urls', namespace='users')),


]

apps/courses/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import CourseListView, CourseDetailView, CourseLessonView, CourseCommentsView, CourseVideoView

app_name = 'courses'
urlpatterns = [

    path('list/', CourseListView.as_view(), name='list'),
    path('<int:course_id>/detail/', CourseDetailView.as_view(), name='detail'),
    path('<int:course_id>/lesson/', CourseLessonView.as_view(), name='lesson'),
    path('<int:course_id>/comments/', CourseCommentsView.as_view(), name='comments'),
    path('<int:course_id>/video/<int:video_id>', CourseVideoView.as_view(), name='video'),

]

apps/operations/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import AddFavView, CommentView


app_name = 'operations'
urlpatterns = [
    path('fav/', AddFavView.as_view(), name='fav'),
    path('comment/', CommentView.as_view(), name='comment'),
    # path('add_ask/', AddAskView.as_view(), name='add_ask'),
    #
    # path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    # path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    # path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    # path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),
]

apps/organization/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Eric Zhu'
__date__ = '2020/2/5 7:32 上午'

from django.urls import path

from .views import OrgView, AddAskView, OrgHomeView, OrgTeacherView, OrgCourseView, OrgDescView, TeachersView
from .views import TeacherDetailView

app_name = 'organization'
urlpatterns = [
    path('list/', OrgView.as_view(), name='list'),
    path('add_ask/', AddAskView.as_view(), name='add_ask'),

    path('<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    path('<int:org_id>/teacher', OrgTeacherView.as_view(), name='teacher'),
    path('<int:org_id>/course', OrgCourseView.as_view(), name='course'),
    path('<int:org_id>/desc', OrgDescView.as_view(), name='desc'),

    path('teachers/', TeachersView.as_view(), name='teachers'),
    path('teachers/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/courses/models.py
# _*_ encoding:utf-8 _*_
"""
    3-Courses 课程主数据
        3.1 Course              课程基本信息
        3.2 Lesson              章节信息
        3.3 Video               视频
        3.4 CourseResource      课程资源
"""

from django.db import models

from users.models import BaseModel
from apps.organization.models import Teacher, CourseOrg

# Create your models here.

DEGREE_CHOICES = (
    ("cj", "初级"),
    ("zj", "中级"),
    ("gj", "高级"),
)


class Course(BaseModel):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name=u"讲师")
    course_org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name=u"课程机构")
    name = models.CharField(max_length=50, verbose_name=u"课程名")     # 所有字段没有特殊指定时，默认为必填项
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    degree = models.CharField(choices=DEGREE_CHOICES, max_length=2, verbose_name=u"难度")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    notice = models.CharField(default="", max_length=300, verbose_name=u"课程公告")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name=u"")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10)
    youneed_know = models.CharField(default="", max_length=300, verbose_name=u"课程须知")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name=u"老师告诉你")

    is_classics = models.BooleanField(default=False, verbose_name=u"是否经典")
    is_banner = models.BooleanField(default=False, verbose_name=u"是否广告位")

    detail = models.TextField(verbose_name=u"课程详情")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        return self.lesson_set.all().count()


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    tag = models.CharField(max_length=100, verbose_name=u"标签")

    class Meta:
        verbose_name = u"课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(BaseModel):
    # on_delete 表示对应的外键数据被删除后，当前的数据将如何处理。
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    url = models.CharField(max_length=1000, verbose_name=u"访问地址")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"下载地址", max_length=200)

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/courses/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from pure_pagination import Paginator, PageNotAnInteger

from apps.courses.models import Course, CourseTag, CourseResource, Video
from apps.operations.models import UserFavorite, UserCourses, CourseComments


class CourseVideoView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, course_id, video_id, *args, **kwargs):
        """
        获取课程详情
        """
        course_detail = Course.objects.get(id=int(course_id))
        course_detail.click_nums += 1
        course_detail.save()

        course_video = Video.objects.get(id=int(video_id))

        # 查询用户是否已经关联了该课程
        user_courses = UserCourses.objects.filter(user=request.user, course=course_detail)
        if not user_courses:
            user_course = UserCourses(user=request.user, course=course_detail)
            user_course.save()

            course_detail.students += 1
            course_detail.save()

        # 学习过该课程的所有同学
        user_courses = UserCourses.objects.filter(course=course_detail)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourses.objects.filter(user_id__in=user_ids).order_by("-course__click_nums")[:5]
        # related_courses = [user_course.course  for user_course in all_courses if user_course.id != course_detail.id]
        related_courses = []
        for item in all_courses:
            if item.course.id != course_detail.id:
                related_courses.append(item.course)

        course_resources = CourseResource.objects.filter(course=course_detail)

        return render(request, 'courses/course-play.html', {
            "course_detail": course_detail,
            "course_resources": course_resources,
            "related_courses": related_courses,
            "course_video": course_video,
        })


class CourseCommentsView(LoginRequiredMixin, View):
    login_url = '/login/'
    def get(self, request, course_id, *args, **kwargs):
        """
        获取课程详情
        """
        course_detail = Course.objects.get(id=int(course_id))
        course_detail.click_nums += 1
        course_detail.save()

        comments = CourseComments.objects.filter(course=course_detail)

        # 查询用户是否已经关联了该课程
        user_courses = UserCourses.objects.filter(user=request.user, course=course_detail)
        if not user_courses:
            user_course = UserCourses(user=request.user, course=course_detail)
            user_course.save()

            course_detail.students += 1
            course_detail.save()

        # 学习过该课程的所有同学
        user_courses = UserCourses.objects.filter(course=course_detail)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourses.objects.filter(user_id__in=user_ids).order_by("-course__click_nums")[:5]
        # related_courses = [user_course.course  for user_course in all_courses if user_course.id != course_detail.id]
        related_courses = []
        for item in all_courses:
            if item.course.id != course_detail.id:
                related_courses.append(item.course)

        course_resources = CourseResource.objects.filter(course=course_detail)

        return render(request, 'courses/course-comment.html', {
            "course_detail": course_detail,
            "course_resources": course_resources,
            "related_courses": related_courses,
            "comments": comments,
        })


class CourseLessonView(LoginRequiredMixin, View):
    login_url = '/login/'
    def get(self, request, course_id, *args, **kwargs):
        """
        获取课程详情
        """
        course_detail = Course.objects.get(id=int(course_id))
        course_detail.click_nums += 1
        course_detail.save()

        # 查询用户是否已经关联了该课程
        user_courses = UserCourses.objects.filter(user=request.user, course=course_detail)
        if not user_courses:
            user_course = UserCourses(user=request.user, course=course_detail)
            user_course.save()

            course_detail.students += 1
            course_detail.save()

        # 学习过该课程的所有同学
        user_courses = UserCourses.objects.filter(course=course_detail)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourses.objects.filter(user_id__in=user_ids).order_by("-course__click_nums")[:5]
        # related_courses = [user_course.course  for user_course in all_courses if user_course.id != course_detail.id]
        related_courses = []
        for item in all_courses:
            if item.course.id != course_detail.id:
                related_courses.append(item.course)

        course_resources = CourseResource.objects.filter(course=course_detail)

        return render(request, 'courses/course-video.html', {
            "course_detail": course_detail,
            "course_resources": course_resources,
            "related_courses": related_courses,
        })


class CourseDetailView(View):
    def get(self, request, course_id, *args, **kwargs):
        """
        获取课程详情
        """
        course_detail = Course.objects.get(id=int(course_id))
        course_detail.click_nums += 1
        course_detail.save()

        # 获取收藏状态
        has_fav_course = False
        has_fav_org = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course_detail.id, fav_type=1):
                has_fav_course = True
            if UserFavorite.objects.filter(user=request.user, fav_id=course_detail.course_org.id, fav_type=2):
                has_fav_org = True

        # 通过课程的tag做课程的推荐
        # tag = course_detail.tag
        # related_courses = []        # 初始化为了避免在template中for循环出错-如果没有找到类型的课程的话
        # if tag:                     # 排除掉自身之外多个课程. excluded(id__in=[course_detail.id])
        #     related_courses = Course.objects.filter(tag=tag).exclude(id__in=[course_detail.id])[:3]

        tags = course_detail.coursetag_set.all()
        tag_list = [tag.tag for tag in tags]
        course_tags = CourseTag.objects.filter(tag__in=tag_list).exclude(course__id=course_detail.id)
        related_courses = set()     # 使用set避免重复的值
        for course_tag in course_tags:
            related_courses.add(course_tag.course)

        return render(request, 'courses/course-detail.html', {
            "course_detail": course_detail,
            "has_fav_course": has_fav_course,
            "has_fav_org": has_fav_org,
            "related_courses": related_courses,
        })


class CourseListView(View):
    """
    获取课程列表信息
    """
    def get(self, request, *args, **kwargs):
        all_courses = Course.objects.order_by("-add_time")
        hot_courses = Course.objects.order_by("-click_nums")[:3]

        # 按关键字搜索
        keywords = request.GET.get("keywords", "")
        s_type = "course"
        if keywords:
            all_courses = all_courses.filter(Q(name__icontains=keywords)|Q(desc__icontains=keywords)|Q(detail__icontains=keywords))

        # 对课程进行排序
        sort = request.GET.get("sort", "")
        if sort == "students":
            all_courses = all_courses.order_by("-students")
        elif sort == "hot":
            all_courses = all_courses.order_by("-click_nums")

        # 对课程列表数据进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_courses, per_page=3, request=request)
        courses = p.page(page)

        return render(request, "courses/course-list.html", {
            "all_courses": courses,
            "sort": sort,
            "hot_courses": hot_courses,
            "keywords": keywords,
            "s_type": s_type,
        })

apps/courses/templates/courses/course-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}  课程列表页 - 慕学在线网{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>课程列表</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block content %}
<section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% ifequal sort '' %}class="active"{% endifequal %}><a href="?sort=">最新 </a></li>
						<li {% ifequal sort 'hot' %}class="active"{% endifequal %}><a href="?sort=hot">最热门</a></li>
						<li {% ifequal sort 'students' %}class="active"{% endifequal %}><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">

                        {% for course in all_courses.object_list %}
                            <div class="box">
                                <a href="{% url 'courses:detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:detail' course.id%}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">点击人数：{{ course.click_nums }}   学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'courses:detail' course.id%}"><span class="fl">来自{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}

					</div>

                        <div class="pageturn">
            <ul class="pagelist">
                {% if all_courses.has_previous %}
                    <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a></li>
                {% endif %}

                {% for page in all_courses.pages %}
                    {% if page %}
                        {% ifequal page all_courses.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                    {% else %}
                        <li class="none">...</li>
                    {% endif %}
                {% endfor %}
                {% if all_courses.has_next %}
                        <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a> </li>
                {% endif %}

            </ul>
        </div>

				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for hot_course in hot_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{{ hot_course.image.url }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> {{ hot_course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ hot_course.get_degree_display }}</i></span>
						</dd>
					</dl>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

apps/courses/templates/courses/course-video.html
{% extends 'base.html' %}
{% load static %}

{% block title %}  公开课视频信息 - 慕学在线网{% endblock %}

{% block custom_css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">

{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:list' %}">公开课</a>></li>
				<li><a href="{% url 'courses:detail' course_detail.id %}">课程详情</a>></li>
                <li>章节信息</li>

            </ul>
        </div>
    </section>
{% endblock %}


{% block content %}

   <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course_detail.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course_detail.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course_detail.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course_detail.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'courses:lesson' course_detail.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:comments' course_detail.id%}"><span>评论</span></a></li>
                    </ul>
                </div>
                {% if course_detail.notice %}
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course_detail.notice }}</a> </div>
                </div>
                {% endif %}

                <div class="mod-chapters">
                    {% for lesson in course_detail.lesson_set.all %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i> {{ lesson.name }} </strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.video_set.all %}
                            <li>
                                <a target="_blank" href="{% url 'courses:video' course_detail.id video.id %}" class="J-media-item studyvideo">{{ video.name }}({{ video.learn_times }}分钟)
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    {% endfor %}

                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ resource.file.url }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'org:teacher_detail' course_detail.id %}" target="_blank">
                                <img src='{{ course_detail.teacher.image.url }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'org:teacher_detail' course_detail.id %}" target="_blank">{{ course_detail.teacher.name }}</a>
        </span>
                            <span class="job">{{ course_detail.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course_detail.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course_detail.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for course in related_courses %}
                                    <li class="curr">
                                        <a href="{% url 'courses:detail' course.id %}" target="_blank">
                                            <img src="{{course.image.url}}" alt="{{course.name}}">
                                            <span class="name autowrap">{{course.name}}</span>
                                        </a>
                                    </li>
                                    {% endfor %}


                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}